const db = require('../db')
const { Coffee } = require('../model')
const { Spice }  = require('../model')
const { Teff } = require('../model')
 
db.on('error', console.error.bind(console, 'MongoDB connection error:'))

const main = async () => {
    const coffee = [
        {type: `Coffee`, name: 'Yirgacheffe Coffee', image: `images/YirgacheeCoffee.png`, description: 'Sourced from the Yirgacheffe region of Ethiopia, Yirgacheffe Magic is gorgeously sweet with lush fruit-tones, including orangey citrus, blueberry, dark chocolate, apple cider, and cherry blossom. With a silky and lively mouth-feel, rich acidity, and deeply flavor-saturated finish, you will love the Yirgacheffe Magic in any roast.', price:40 },
        {type: `Coffee`, name: 'Harrar Coffee', image: `images/HarrarCoffee.png`, description: 'Sourced from the Harrar region of Ethiopia, this organic single origin coffee features a rich flavor that is dazzlingly aromatic and fruity. With awesome blueberry notes, dark chocolate and a magical creamy body, you will love the Harrar Regal.', price: 40 },
        {type: `Coffee`, name: ' Sidamo Coffee', image: `images/sidamoCoffee.png`, description: ' Sourced from the Sidamo region in Ethiopia, this organic single-origin coffee features a taste of delicious fruity flavours combined with a sweet, magical body. Each sip contains some chocolate hints, along with notes of lemon, jasmine and lavender. You will certainly discover even more flavors and tastes. ', price: 40 },
        {type: `Coffee`, name: 'Wollega Coffee', image: `images/wollegaCoffee.png`, description: 'Sourced from the Wollega region of Ethiopia, this organic single-origin coffee is mind-blowingly clean. With a deliciously fruity and sweet flavour and a magical body, you will love each sip of the Wollega Ultimate.', price: 40 }
    ]
    await Coffee.deleteMany()
    await Coffee.insertMany(coffee)
    console.log('Created some coffees!')

    const spice = [
        {type: `spice`, name: 'Limut Shiro | Shiro Stew Blend', image: `images/limutshiro.png`, price: 25.99 ,ingredient:'ground Ethiopian chickpeas, yellow peas, fava beans, garlic, ginger, holy basil, thyme, rosemary, fenugreek, and ajowan.', description:'Shiro powder is used to make shiro wot, Ethiopias national dish. This is the stew you will find on every dinner table in every Ethiopian household up and down the country. It is mild and has a lovely creamy texture.This Shiro blend is made with roasted Ethiopian chickpeas, yellow peas, fava beans, and a bouquet of fresh herbs and sun-dried spices. Limut shiro does not contain berbere. This allows the pulses to really come into their own, giving limut a subtle earthy flavour. Just like our other shiro variety, limut is easy to prepare and ready in a jiffy.' },
        {type: `spice`, name: 'Berbere | Ethiopian Red Chili Blend', image: `images/berbere.png`, price: 22.99 , ingredient:'Ethiopian red pepper, ajowan, nigella seeds, coriander, fenugreek, clove, cassia seeds, garlic, ginger, and onion.',  description:'Berbere is the queen of Ethiopian spice blends. There is hardly a dish that doesnt rely on its fiery notes. The blend is built around the berbere chilli. Combined with various other herbs and spices, this chilli gives a lovely depth of flavour. Every household has its own recipe so every berbere is different. Our blend uses etalls original recipe.Berbere is used to make miser wot, squash wot, tofu tibs, awaze, and many other dishes. Berbere is at home in Ethiopian dishes but loves to be taken out of its comfort zone. Add it to sauces, soups, marinades, and roasts. Why not mix it with a little red wine, mustard, and honey to create a scrumptious dip? This versatile blend will not disappoint! ' },
        {type: `spice`, name: 'Mitten Shiro | Shiro Stew Blend with Berbere', image: `images/mittenshiro.png`, price: 23.99 ,ingredient:'ground Ethiopian chickpeas, yellow peas, fava beans, garlic, ginger, holy basil, thyme, rosemary, fenugreek, berbere chilli, ajowan, nigella seeds, coriander, clove, cassia seeds, and onion powder.',  description:' Shiro powder is used to make shiro wot, Ethiopias national dish. This is the stew you will find on every dinner table in every Ethiopian household up and down the country. It is mild and has a lovely creamy texture.This Shiro blend is made with roasted Ethiopian chickpeas, yellow peas, fava beans, and a bouquet of fresh herbs and sun-dried spices. Its also called mitten shiro because it contains a little bit of berbere, giving it a lively orange colour. This dish will make your beyaynetu (platter with various dishes) complete. Its easy to make and ready in no time at all.' },
        {type: `spice`, name: 'Korerima | Ground Ethiopian cardamom', image: `images/korerima.png`, price: 25.99 , ingredient:'Ethiopian cardamom',  description:'Ethiopian cardamom (also known as false cardamom) is one of the essential spices in Ethiopian cooking and probably the most expensive. It is part of the ginger family and tastes a bit like green cardamom, but it’s both more delicate and more intense. The flavour can be described as smoky and peppery with a touch of mint.Korerima is a key ingredient in many of our spice blends. It can be used in the same way as black pepper, but use it sparingly and only when you want to impress! Our Ethiopian cardamom is pre-shelled, dried, roasted, and ground, and is ready for use.' },
        {type: `spice`, name: 'Mitmita | African Bird Eye Chili Blend', image: `images/mitmita.png`, price: 27.99 , ingredient:'African birds-eye chili pepper, Ethiopian cardamom, salt.',  description:'Mitmita is the most dangerous of Ethiopian spice blends. Watch out, an overdose can be fatal. Thats why we are selling this one in small quantities only.Mitmita is mainly used for dipping. You will often see this bright, terracotta-coloured powder sitting on the edge of a plate of injera (Ethiopian flatbread). It is for you to dunk your "gursha" in. Enjoy and feel yourself transported to warmer places! Its also delicious in fruit salads (think mango and pineapple with a sprig of mint) or on avocado toast – one of our personal favourites. Its muscular flavour profile also works great in marinades and barbeques.' },
        {type: `spice`, name: 'Qibbeh Manteria | Ethiopian Butter Spice Blend ', image: `images/qibbehManteria.png`, price: 22.99 , ingredient:' koseret, korerima, holy basil, thyme, dried garlic, Ethiopian black cumin (nigella seeds), Ethiopian caraway seeds (ajowan), and fenugreek.' ,  description:'   Nitter qibbeh is a spiced clarified butter traditionally made with cows milk, but it can also be made with non-dairy butter or with oil. The process of clarification separates the fat from the milk solids and water. The result is a highly flavourful cooking fat. It has a higher smoke point and longer shelf life than regular butter.As it is difficult to get hold of the spices used for clarification, we have created our own blend which will help you make nitter qibbeh at home. Amaarechs recipe uses premium ingredients, bringing out the distinctive qibbeh aromatics. Having a supply of nitter qibbeh in your fridge allows you to add flavour to your cooking in an easy and efficient manner. We usually add qibbeh at the end of the cooking process to round out the flavours. '},
        {type: `spice`, name: 'Mekelesha | Seven Spice Rounding off Blend', image: `images/mekelesha.png`, price: 21.99 , ingredient:'Ethiopian nutmeg (gewz), Ethiopian cardamom (korerima), cinnamon, black pepper, cumin, Indian long pepper (timiz), and cloves.',  description:'Mekelesha is the secret ingredient that will lift your stews to the next level of food heaven. The blend consists of seven hand-roasted spices selected by Amaarech herself. Among them are Ethiopian cardamom, nutmeg, and pepper, giving this blend an autumny profile. Our mekelesha is very concentrated so a little goes a long way.' },
        {type: `spice`, name: 'Tibes Qimmem | Roasting Blend', image: `images/tibesQimmem.png`, price: 19.99 , ingredient:' rosemary, korerima, black pepper, and garlic.',  description:'  The literal meaning of tibs qimmem is "roasting spice". We developed this blend ourselves so you won’t find it anywhere else. Tibs qimmem is inspired by the dish that goes by the same name, tibs: beef or lamb stir-fried with onion, garlic, qibbeh, and fresh rosemary. We have created an all-in-one blend to help you recreate this dish or to experiment on your own!Our blend is perfect for flavouring vegetables. Think of it as the Ethiopian version of herbes de provence. Our blend is highly concentrated so a little goes a long way. It is particularly suited to enliven casseroles, oven roasts, and stir-fries.' },
        {type: `spice`, name: 'Nech Qimmem | Ethiopian Caraway Seed Blend', image: `images/nechQimmem.png`, price: 18.99,  ingredient:'ajowan, korerima, and dried garlic. ',  description:'Nech qimmem means white spice and we mainly use it in mild, light-coloured stews and sauté.Amaarechs original recipe uses Ethiopian caraway seeds (also referred to as ajowan or bishops weed), korerima, and garlic, which are washed, dried, toasted, ground, and blended together. Nech qimmem has notes of cumin, oregano, and thyme. It will add flavour to any vegetable dish and is also great in roasts. ' },
        {type: `spice`, name: 'Tikur Qimmem | Ethiopian Black Cumin Blend', image: `images/tikurQimmem.png`, price:17.99, ingredient:'nigella seeds, dried garlic, holy basil, and korerima.',  description:'Tikur qimmem means black spice and is intended to go in dark, spicy, red stews.The main ingredient is Ethiopian black cumin (nigella seeds), giving tikur qimmem its distinct smoky flavour. The korerima adds a minty note. We mainly use this blend in spicy red stews but it is a great addition to sautés too.' },
        
        
    ]
    await Spice.deleteMany()
    await Spice.insertMany(spice)
    console.log('Created some Spices!')


    const teff = [
        {type: `teff`, name: 'Et Teff flour', image: `images/teffFlour.png`, price:20.99, description: 'Teff is a naturally gluten-free grain packed with lots of nutrients and minerals. It is a staple food in Ethiopia and across the Horn of Africa. In Ethiopia, it is mainly used to make injera, a fermented sourdough pancake-like bread.', productInfo:'Our Et teff flour is made from 100% Ethiopian teff grain. It is stone-milled to maintain its natural flavour. Teff flour can be used to make injera or as a healthy and gluten-free substitute in baking and cooking.' },
        {type: `teff`, name: 'Et Brown Teff Flour', image: `images/brownTeffFlour.png`, price: 20.99, description: 'Teff is a naturally gluten-free grain packed with lots of nutrients and minerals. It is a staple food in Ethiopia and across the horn of Africa. In Ethiopia, it is mainly used to make injera, a fermented sourdough pancake-like bread.', productInfo:'Our brown teff flour is made from 100% Ethiopian teff grain. It is stone-milled to maintain its natural flavours. Teff flour can be used to make injera or as a healthy and gluten-free substitute in baking and cooking. ' },
        
    ]
    await Teff.deleteMany()
    await Teff.insertMany(teff)
    console.log('Created some Teffs!')
}
const run = async () => {
    await main()
    db.close()
}

run()